Ap/add codable
IntrepidPursuits/webservices-example-ios pull request #2
Opened 2018-01-08 14:38 UTC by alexpersian

Adds a `ColorData` model which is then used to directly convert the JSON data received.

2018-01-08 16:15 UTC, wingchi approved these changes
Edit: See other change request.

2018-01-08 16:15 UTC, wingchi commented on consuming-webservices/ViewModel.swift
> +                    self.color = currentColor
For consistency either directly assign `UIColor(colorData.color)` to self.color like in `setColor` or add `currentColor` to `setColor`

2018-01-08 16:26 UTC, wingchi requested changes
Oh wait, you can probably use encode to create the body for your request instead of `request.httpBody = try JSONSerialization.data(withJSONObject: body, options: [])` on line 64 of RequestHandler.swift

2018-01-08 17:31 UTC, alexpersian commented
Good catch. I missed that encode addition

2018-01-09 05:32 UTC, wingchi approved these changes
:shipit:

2018-01-09 14:47 UTC, merged